package com.github.jorepong.safetycctv.entity;

import com.github.jorepong.safetycctv.alert.AlertLevel;
import com.github.jorepong.safetycctv.alert.AlertType;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Represents a safety alert event generated by the system.
 */
@Entity
@Table(name = "safety_alerts")
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SafetyAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The camera that triggered this alert.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "camera_id")
    private Camera camera;

    /**
     * The timestamp when the alert was generated.
     */
    @Column(nullable = false)
    private LocalDateTime timestamp;

    /**
     * The type of event that triggered the alert.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private AlertType alertType;

    /**
     * The severity level of the alert.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private AlertLevel alertLevel;

    /**
     * A detailed message describing the alert.
     * e.g., "Density reached 0.78, exceeding the threshold of 0.6."
     */
    @Column(nullable = false, length = 512)
    private String message;

    /**
     * The ID of the analysis log that is directly associated with this alert, if
     * applicable.
     */
    @Column(name = "analysis_log_id", insertable = false, updatable = false)
    private Long analysisLogId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "analysis_log_id")
    private AnalysisLog analysisLog;

    /**
     * A flag indicating whether this alert has been acknowledged or resolved by an
     * operator.
     */
    @Builder.Default
    @Column(nullable = false)
    private boolean resolved = false;

    /**
     * The timestamp when the alert was marked as resolved.
     */
    private LocalDateTime resolvedAt;

    @PrePersist
    protected void onCreate() {
        if (this.timestamp == null) {
            this.timestamp = LocalDateTime.now();
        }
    }
}
